### PR TITLE
Added Metadata for Nifi 1.2.0

### PR DESCRIPTION
**Pull request by jomach**
based on https://bryanbende.com/development/2017/05/10/apache-nifi-1-2-0-component-versioning

This project is old but we need it...

### CODE REVIEW

**Comment by sponiro** [comment]
Thank you for your contribution! I might need some time to incorporate your changes. In the meantime you might work around this by adding the manifest entries in your build.gradle in the nar task. The nar task extends class Jar and so the documentation from https://docs.gradle.org/current/userguide/java_plugin.html#sec:jar applies.

**Comment by jomach** [comment]
@sponiro I'm really a rookie on ruby and I have tryed that and failed. The problem: 
We need that the first Manifest has this information, I have subprojects and if I use this jar example it will put the information into the wrong metainf. For Example: 

- maNarFile.nar:
  - META-INF:
    - MANIFEST.MF <--- The Metadata Info needs to be here
    - bundled-dependencies:
      - myjarFileFRomSubProject.jar <---- If I use that jar task the Metadata lands inside this JAR

**Comment by jomach** [comment]
PS: Can you convert the project to UTF-8 ?

**Comment by sponiro** [comment]
Gradle uses Groovy for its build scripts. To change the manifest you have to add the following code to your build.gradle. Make sure you put it in the correct build file!
```groovy
nar {
    manifest {
        attributes 'Nar-Group': project.group, 'Nar-Id': project.name, 'Nar-Version': project.version
    }
}
```
In a test this worked for me.
When I release a new version I will also check for the encoding to make sure it is always UTF-8.

**Comment by jomach** [comment]
This works really go. thanks by the way the structure has changed from the files too.

**Comment by jomach** [comment]
should I close this PR  then ?

**Comment by sponiro** [comment]
I will consider these changes for the next version. For now I close this PR.

**Pull request closed without merging**
